# Numpy Questions:

In [11]:
import numpy as np

def merge(a, b):
    return np.maximum(a, np.reshape(b, shape=a.shape)).astype(float)

a = np.array([[0,20,4],[7,1,3]])
b= np.array([0,1,2,3,4,5])

print(merge(a, b))

[[ 0. 20.  4.]
 [ 7.  4.  5.]]


In [18]:
import numpy as np

def demean(a):
    return a - np.mean(a, axis=0)

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
])

# np.mean(a) -> Mean of the whole vector/matrix (scalar) a ∈ R
# np.mean(a, axis=0) -> Mean per column of the vector/matrix (vector). If a ∈ R ^mxn -> a_mean ∈ R^1xn
# np.mean(a, axis=1) -> Mean per row of the vector/matrix (vector) If a ∈ R ^mxn -> a_mean ∈ R^1xm

demean(a)

array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

In [31]:
import numpy as np

def colsum(a: np.ndarray) -> np.ndarray:
    return np.array([np.sum(a[::, ::2]), np.sum(a[::, 1::2])])

a= np.array([
    [2, 7, 8, 0],
    [3, 9, 3, 4],
    [4, 0, 1, 3],
])

# a ∈ R^(n, p), p>=2 -> a ∈ R^(1, 2)

colsum(a)

array([21, 23])

In [34]:
import numpy as np

def count_common(a, b):
    return np.sum( a == b)

a = np.array([[1,3,8],
              [4,5,2],
              [3,2,9]])

b = np.array([[2,3,7],
              [4,5,9],
              [6,6,6]])

count_common(a, b)

np.int64(3)

In [40]:
import numpy as np

def foo(i, j):
    return (i + j) % 2

def checkerboard(m):
    return np.fromfunction(foo, (m, m), dtype=int)

checkerboard(m=2)

array([[0, 1],
       [1, 0]])

In [66]:
import numpy as np


def zeroones(p: np.ndarray, q: np.ndarray):
    zeros = np.zeros(shape=(p, q))
    inner_rows, inner_columns = p - 2, q - 2

    inner_arrays = np.arange(start=1, stop=(inner_rows * inner_columns) + 1, step=1).reshape(inner_rows, inner_columns)
    zeros[1:-1, 1:-1] = inner_arrays

    return zeros

p, q = 4, 8
zeroones(p, q)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  0.],
       [ 0.,  7.,  8.,  9., 10., 11., 12.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [79]:
import numpy as np

def zerocolumns(a: np.ndarray) -> np.ndarray:
    return a[:, np.all( a != 0, axis=0)]


a = np.array([
    [1,2,0],
    [3,1,1],
    [3,3,0]
])

zerocolumns(a)

array([[1, 2],
       [3, 1],
       [3, 3]])

In [95]:
import numpy as np

def foo(i, j, x0=0, y0=0):
    return np.sqrt((i - x0) ** 2 + (j - y0) ** 2)

def arraydistance(p: int, q: int, x0: int=0, y0: int=0) -> np.ndarray:
    return np.fromfunction(lambda i, j: foo(i, j, x0=x0, y0=y0), shape=(p, q), dtype=float)

p, q = 3, 3
x0, y0 = 0, 0

arraydistance(p, q)

array([[0.        , 1.        , 2.        ],
       [1.        , 1.41421356, 2.23606798],
       [2.        , 2.23606798, 2.82842712]])

In [116]:
import numpy as np

def lowest(a, b):
    return np.lcm.outer(a, b)

a = np.arange(0, 10)
b = np.arange(0, 5)

lowest(a, b)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  2,  6,  4],
       [ 0,  3,  6,  3, 12],
       [ 0,  4,  4, 12,  4],
       [ 0,  5, 10, 15, 20],
       [ 0,  6,  6,  6, 12],
       [ 0,  7, 14, 21, 28],
       [ 0,  8,  8, 24,  8],
       [ 0,  9, 18,  9, 36]])

In [165]:
import numpy as np

def element(a: np.ndarray, p: int):
    return -1 if (p >= a.size or p < 0) else a.flatten()[p]


p = 0
a = np.array([
    [[4,3,6],[3,2,8]],
    [[1,5,7],[2,6,7]],
    [[3,6,7],[3,7,4]],
    [[4,2,7],[4,3,1]],
    [[5,3,5],[3,6,5]],
])

print(element(a, p))
print(element(np.array([[[4,3,6],[3,2,8]],[[1,5,7],[2,6,7]],[[3,6,7],[3,7,4]],[[4,2,7],[4,3,1]],[[5,3,5],[3,6,5]]]), 0))
print(element(np.array([[[4,3,6],[3,2,8]],[[1,5,7],[2,6,7]],[[3,6,7],[3,7,4]],[[4,2,7],[4,3,1]],[[5,3,5],[3,6,5]]]), 5))
print(element(np.array([[[4,3,6],[3,2,8]],[[1,5,7],[2,6,7]],[[3,6,7],[3,7,4]],[[4,2,7],[4,3,1]],[[5,3,5],[3,6,5]]]), 29))
print(element(np.array([[[4,3,6],[3,2,8]],[[1,5,7],[2,6,7]],[[3,6,7],[3,7,4]],[[4,2,7],[4,3,1]],[[5,3,5],[3,6,5]]]), 30))

4
4
8
5
-1


In [216]:
import numpy as np

def exchangecolumns(a: np.ndarray):
    _, columns = a.shape

    if columns % 2 == 1:
        return None
    
    even_columns, odd_columns = a[:,0::2].copy(), a[:,1::2].copy()
    a[:,0::2], a[:,1::2] = odd_columns, even_columns

    return a

a = np.arange(0, 6).reshape(3, 2)
print(exchangecolumns(a))
	
print(exchangecolumns(np.arange(0,20).reshape(5,4)))
	
print(exchangecolumns(np.arange(0.,12.).reshape(3,4)))
print(exchangecolumns(np.arange(0,25).reshape(5,5)))
print(exchangecolumns(np.array([[3,42,5,11,44,55],[7,9,4,1,3,2]])))


[[1 0]
 [3 2]
 [5 4]]
[[ 1  0  3  2]
 [ 5  4  7  6]
 [ 9  8 11 10]
 [13 12 15 14]
 [17 16 19 18]]
[[ 1.  0.  3.  2.]
 [ 5.  4.  7.  6.]
 [ 9.  8. 11. 10.]]
None
[[42  3 11  5 55 44]
 [ 9  7  1  4  2  3]]


In [8]:
import numpy as np

def multiply_rows(A, B):
    return np.array([A[0, :] * B[0], A[1, :] * B[1]])

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([2, 3])


print(multiply_rows(A, B))


[[ 2  4  6]
 [12 15 18]]


In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
Am = np.mean()
