In [229]:
def foo(L):
    freq = {v: L.count(v) for v in L}
    freq_items = list(freq.items())
    freq_sorted = sorted(freq_items, key= lambda item: item[1], reverse=False)
    return [i[0] for i in freq_sorted]
L = [1,2,2,3,3,3,3]

freq = {v: L.count(v) for v in L}
freq_items = list(freq.items())
freq_sorted = sorted(freq_items, key= lambda item: item[1], reverse=False)
[i[0] for i in freq_sorted]

[1, 2, 3]

In [232]:
from math import sqrt

def first_degree(a,b):
    try:
        x = -b/a
        return round(x, 2)
    
    except ZeroDivisionError:
        
        try:
            y = 1/b
            return "no solutions: a==0 and b!=0"
        
        except ZeroDivisionError:
            return "trivial: a==0 and b==0"

print(first_degree(2, -10))

5.0


In [245]:
def sum_one_inplace(L, p=0):
    for i in range(p, len(L)):
        L[i] += 1

def all_fair(L):
    return all([L[i + 1] != L[i] + 1 for i in range(len(L) - 1)])

def fair(L):
    fair_init = all_fair(L=L)

    while not all_fair(L):
        for i in range(len(L) - 1):
            if L[i + 1] == L[i] + 1:
                sum_one_inplace(L, i + 1)
                break

    return fair_init, L



X=[1,2,6,9,10]
idX=id(X)
FX=fair(X)
print(FX, id(FX[1])==idX)

W=[1,3,5,7,9]
idW=id(W)
FW=fair(W)
print(FW,id(FW[1])==idW)

(False, [1, 3, 7, 10, 12]) True
(True, [1, 3, 5, 7, 9]) True


In [249]:
class Number:

    def __init__(self, x):
        self.x = x 

    def __mul__(self: "Number", other: "Number"):
        return self.x * other.x

class A(Number): ...

class B(Number):

    def __mul__(self, other):
        return - super().__mul__(other)
    
print(A(3)*B(5))
print(B(3)*A(5))

15
-15


In [254]:
def exhaustgen(G):
    try:
        while G:
            next(G)
    except StopIteration:
        pass

exhaustgen(i for i in range(4))
exhaustgen(print(i) for i in range(4))



0
1
2
3


In [257]:
def my_update(D1,D2):
    for k, v in D2.items():

        if k not in D1.keys():
            D1[k] = v
        else:
            D1[k] = D2[k] + D1[k]




D1={1:'10',2:20}
D2={1:'100',3:30}
my_update(D1,D2)
print(D1=={1: '10010', 2: 20, 3: 30},D2=={1: '100', 3: 30})

True True


In [264]:
class A(Exception): ...

class B(A):

    def __init__(self, b):
        self.b = b 
    
    def __str__(self):
        return str(self.b)

try:
    raise B(10)
except A as x:
    print(x)

10


In [286]:
def without_pick(L):
    return all([not (L[i-1]<L[i]>L[i + 1]) for i in range(1, len(L) - 1)])

def spicca(L):
    while not without_pick(L):
        i, L_size = 1, len(L) - 1
        while i < L_size:
            
            if L[i-1]< L[i] >L[i + 1]:
                del L[i]
                break

            else:
                i += 1

    return L

L = [1,3,4,0,9,6,8,7,2]
print(spicca([1,3,4,0,9,6,8,7,2]))


[1, 0, 2]


In [287]:
print(spicca(L))
print(spicca([]))
print(spicca([1]))
print(spicca([1,3]))
print(spicca([1,2,3]))
print(spicca([1,3,1]))
print(spicca([1,2,3,4,5,6,7,-1]))
print(spicca([7,6,5,4,3,2,3,-1]))

[1, 0, 2]
[]
[1]
[1, 3]
[1, 2, 3]
[1, 1]
[1, -1]
[7, 6, 5, 4, 3, 2, -1]


In [290]:
class Top:
    def __init__(self,s):
        if type(s)!=str:
            raise TypeError
        self.__st=s

    def get(self):
        return self.__st
    
class A(Top):

    def __eq__(self: "Top", other: "Top"):
        return self.get() == other.get()
    
class B(A): 
    def __eq__(self: "Top", other: "Top"):
        return self.get() == other.get()[::-1]
    
a1=A('pippo')
a2=A('pippo')
print(a1==a2)

b1=B('pippo')
b2=B('oppip')
print(b1==b2)

True
True


In [ ]:

import numpy as np

np.maximum()


In [291]:
import numpy as np

def min_col(A):
    return np.min(A, axis=0)

A = np.array([[2,4,9],
              [3,2,1],
              [7,3,1]])

print(min_col(A))

[2 2 1]


In [295]:

def new_update(D1, D2):
    keys_to_remove = []
    for k, v in D1.items():
        if k not in D2.keys():
            D2[k] = v
        else:
            keys_to_remove.append(k)

    for k in keys_to_remove:
        del D1[k], D2[k]


D1={1:10,2:20}
D2={1:100,3:30}

# keys_to_remove = []
# for k, v in D1.items():
#     if k not in D2.keys():
#         D2[k] = v
#     else:
#         keys_to_remove.append(k)

# for k in keys_to_remove:
#     del D1[k], D2[k]

# D1, D2
new_update(D1,D2)
print(D1=={2: 20},D2=={2:20, 3: 30})


True True


In [297]:
def printgen(x):
    Xl = list(x)[::-1]
    for i in Xl:
        print(i)

X=(i for i in range(4))
printgen(X)

3
2
1
0


In [338]:
def order_inplace(L):
    n= len(L)
    for i in range(n):
        for j in range(n - i - 1):
            if L[j] > L[j + 1]:
                L[j], L[j + 1] = L[j + 1], L[j]

    return L

L=[10, 1, 11, 22, 3, 5, 23]
L_id = id(L)
Ln = order_inplace(L)
Ln_id = id(Ln)
Ln_id == L_id

True

In [332]:
def move_in_place(L, i=0, f=0):
    for j in range(i, len(L) - 1 - f):
        L[j + 1], L[j] = L[j], L[j + 1]

def to_the_end_inplace(L: list, i: int=0) -> None:
    for j in range(i, len(L) - 1):
        L[j + 1], L[j] = L[j], L[j + 1]

def increasing_order(L):
    return all([L[i]<= L[i + 1] for i in range(len(L) - 1)])

def partition(L):
    n = len(L)
    for i in range(n):
        for j in range(0, n - i - 1):
            if L[j] > L[j + 1]:
                L[j], L[j + 1] = L[j + 1], L[j]

L=[10, 1, 11, 22, 3, 5, 23]


n = len(L)
for i in range(n):
    for j in range(0, n - i - 1):
        if L[j] > L[j + 1]:
            L[j], L[j + 1] = L[j + 1], L[j]

L


0 0 [10, 1, 11, 22, 3, 5, 23]
0 1 [1, 10, 11, 22, 3, 5, 23]
0 2 [1, 10, 11, 22, 3, 5, 23]
0 3 [1, 10, 11, 22, 3, 5, 23]
0 4 [1, 10, 11, 3, 22, 5, 23]
0 5 [1, 10, 11, 3, 5, 22, 23]
1 0 [1, 10, 11, 3, 5, 22, 23]
1 1 [1, 10, 11, 3, 5, 22, 23]
1 2 [1, 10, 11, 3, 5, 22, 23]
1 3 [1, 10, 3, 11, 5, 22, 23]
1 4 [1, 10, 3, 5, 11, 22, 23]
2 0 [1, 10, 3, 5, 11, 22, 23]
2 1 [1, 10, 3, 5, 11, 22, 23]
2 2 [1, 3, 10, 5, 11, 22, 23]
2 3 [1, 3, 5, 10, 11, 22, 23]
3 0 [1, 3, 5, 10, 11, 22, 23]
3 1 [1, 3, 5, 10, 11, 22, 23]
3 2 [1, 3, 5, 10, 11, 22, 23]
4 0 [1, 3, 5, 10, 11, 22, 23]
4 1 [1, 3, 5, 10, 11, 22, 23]
5 0 [1, 3, 5, 10, 11, 22, 23]


[1, 3, 5, 10, 11, 22, 23]

In [335]:
class A:
    def __init__(self,x):
        self.xx = x

class B(A):

    def __init__(self, x, y):
        super().__init__(x)
        self.y = y

    def __str__(self):
        return "B: " + str(self.xx * self.y)
    
b=B(10,20)
print(b)

200


In [336]:
import numpy as np

def filter_ones(A, B):
    return A[B.T == 1]

A = np.array([[7,1,4], [2,5,4]])
B = np.array([[0,1], [1,0],[1,1]])
print(filter_ones(A,B))

[1 4 2 4]


In [337]:
B.T == 1

array([[False,  True,  True],
       [ True, False,  True]])

In [354]:
import numpy as np

def multiply_rows(A, B):
    return A * B[:, np.newaxis]

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([2, 3])


print(multiply_rows(A, B))


[[ 2  4  6]
 [12 15 18]]


In [358]:
# Question 02
import numpy as np

def mean_diff(A):
    return A - np.mean(A, axis=1)[:, np.newaxis]

A = np.array([[1, 2, 3], [4, 5, 6]])
Am = np.mean(A, axis=1)

# A - Am[:, np.newaxis]
print(mean_diff(np.array([[1, 2, 3], [4, 5, 6]])))


[[-1.  0.  1.]
 [-1.  0.  1.]]


In [361]:
# Question 03
import numpy as np

def diagonal_sum(A):
    return np.sum(A.diagonal())

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


print(diagonal_sum(A))



15


In [365]:
# Question 04:

def unique_count(A):
    return np.unique(A).size


A = np.array([[1, 2, 3], [4, 5, 1]])
print(unique_count(A))




5


In [371]:
# Question 05:

def foo(i, j):
    return (i + j) % 2 

def checkerboard(m):
    return np.fromfunction(foo, shape=(m, m))

def checkerboard_sum(m):
    return np.sum(checkerboard(m), dtype=int)

checkerboard_sum(4)

np.int64(8)

In [378]:
# Question 06:

def remove_nan_columns(a):
    return a[:, np.logical_not(np.isnan(a).any(axis=0))]

def remove_nan_rows(a):
    return a[np.logical_not(np.isnan(a).any(axis=1))]


A = np.array([[1, np.nan, 3], [4, 5, 6]])

A[:, ~np.isnan(A).any(axis=0)]


print(remove_nan_columns(A))


[[1. 3.]
 [4. 6.]]


In [379]:
# Question 07:

def foo(i, j):
    return i + j

def distance_matrix(m):
    return np.fromfunction(foo, shape=(m, m), dtype=int)

print(distance_matrix(3))


[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


In [382]:
# Question 08:

def pairwise_lcm(A, B):
    return np.lcm.outer(A, B)

A = np.array([2, 3])
B = np.array([4, 5, 6])

print(pairwise_lcm( A, B))


[[ 4 10  6]
 [12 15  6]]


In [383]:
# Question 09:
def flatten_index(A, p):
    return -1 if p < 0 or p >= A.size else A.flatten()[p]


print(flatten_index(np.array([[1, 2], [3, 4]]), 3))
print(flatten_index(np.array([[1, 2], [3, 4]]), 5))


4
-1


In [398]:
A = np.array([[3], [56]]).reshape(1, -1)
B = np.array([1, -1]).reshape(-1, 1)

A

array([[ 3, 56]])