# Exam 24/20/2023:


Write a function foo(S) that takes a sequence of (possibly repeated) integers S and returns a list of the unique integer values in S, in order of increasing frequency of occurrence in S.
Assume that all the values in S have different frequence of occurrence in S.


In [15]:


def foo(S):
    freq = {}
    for i in S:
        if i in freq:
            freq[i] += 1
        else:
            freq[i] = 1
    return sorted(freq, key=lambda x: freq[x])

print(foo([1,2,1,1,2,3]))




[3, 2, 1]


Without using the if construct,
define the function first_degree(a,b) which returns the solution of the first degree equation ax+b=0
. The function:

if the equation has one solution, returns its value rounded to two decimal digits (use the predefined function round(x,2)).
if the equation has no solutions, returns the string "no solutions: a==0 and b!=0".
if the equation is a trivial identity, returns the string "trivial: a==0 and b==0".

In [61]:
from math import sqrt

def first_degree(a,b):
    try:
        sol = -b/a
        return round(sol, 2)
        
    except ZeroDivisionError:
        
        try:
            b_validation = 1/b
            return "no solutions: a==0 and b!=0"
        
        except ZeroDivisionError:
            return "trivial: a==0 and b==0"
            

A list of integers is fair if there are no contiguous elements with L[i+1]==L[i]+1.

Write a Python function fair(L) which takes a list of integers L and:
- If L is fair, returns the pair
True, L

- if L is not fair (and hence there is a minimal index i for which L[i+1]==L[i]+1), the function modifies L in place, summing one to all elements from L[i+1] to L[-1] included; the function proceeds then to verify the (modified) slice L[i+1:]: if there is a non fair pair L[j+1]==L[j]+1 (remember that L is no longer the original one), it applies again the modification ("sum one"), starting from  L[j+1], etc. The function returns
False, L
where L is the modified list, which is fair by construction.

If possibile, avoid repeated scans of L.

In the automatic tests, the second Boolean value checks that the modification has been done in place.

In [57]:
def add(L, start=0):
    for i in range(start, len(L)):
        L[i] += 1
    return L

def all_fair(X):
    return all([X[i + 1] != X[i] + 1 for i in range(0, len(X) - 1)])


def fair(X):

    initial_fairness = all_fair(X)

    while not all_fair(X):
        for i in range(len(X) - 1):
            if X[i + 1] == X[i] + 1:
                add(X, i + 1)
                break

    return initial_fairness, X

X=[1,3,5,7,9]
idX=id(X)
FX=fair(X)
print(FX, id(FX[1])==idX)

(True, [1, 3, 5, 7, 9]) True


Define a suitable class hierarchy (including the needed methods) so that the command
print(A(3)*B(5))
will print 15, while
print(B(3)*A(5))
will print -15.

More generally, 

print(A(u)*B(v))
should print the product of u and v, while
print(B(u)*A(v))
should print the -u*v.

In [ ]:
class Number:
    def __init__(self, number):
        self.number = number

    def __mul__(self: "Number", other: "Number"):
        return self.number * other.number
    
class A(Number): ...

class B(Number):

    def __mul__(self, other):
        return - super().__mul__(other)




Write a function exhaustgen(G) that when taking a generator object G as argument (you don't need to check this), it simply produces the elements of G, without doing anything with them, until the generator is exhausted. The only visible effects of a call exhaustgen(G), therefore, are the side-effects, if any, produced by the elements of G.

In [60]:
def exhaustgen(G):
    try:
        while G:
            next(G)
    except StopIteration:
        pass

exhaustgen(print(i) for i in range(4))

0
1
2
3


# Exam 11/01/2024:

In [65]:
def my_update(D1, D2):

    for key, value in D2.items():
        
        if key in D1.keys():
            D1[key], D2[key] = D2[key], D1[key]
        else:
            D1[key] = D2[key]
        

D1={1:10,2:20}
D2={1:100,3:30}

my_update(D1,D2)
print(D1=={1: 100, 2: 20, 3: 30},D2=={1: 10, 3: 30})

True True


In [82]:
def printgen(X):
    _X = []
    for x in X:
        _X.append(x)
        print(x)
        
    for x in _X:
        print(x)


X=(i for i in range(4))
printgen(X)

0
1
2
3
0
1
2
3


Write a function merge(L1, L2) which takes as parameters two lists ordered in ascending order (just assume this without checking). It should create and return a third list, also ordered, obtained from the union of the two.

You cannot use the library function sort (or analogous, e.g. sorted). 

In [110]:
def merge(L1, L2):

    L, i, j = [], 0, 0
    while i < len(L1) and j < len(L2):

        l1, l2 = L1[i], L2[j]

        if l1 <= l2:
            L.append(l1)
            i += 1
        else:
            L.append(l2)
            j += 1

    L.extend(L1[i:] if i < len(L1) else L2[j:])
    
    return L

print(merge([1,3,5], [0,2,4,6,8,10]))
print(merge([], []))
print(merge([1,3,5], []))
print(merge([], [1,3,6]))
print(merge([100], list(range(1,99,3))))
print(merge([1,3,5], [100,300,500]))
print(merge([1],[100]))

[0, 1, 2, 3, 4, 5, 6, 8, 10]
[]
[1, 3, 5]
[1, 3, 6]
[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97, 100]
[1, 3, 5, 100, 300, 500]
[1, 100]


In [112]:
class A:
    def __init__(self, x):
        self.xx = x

class B(A):
   
    def __init__(self, x, y):
        super().__init__(x)
        self.yy = y

    def __str__(self):
        return f"B: {self.yy + self.xx}"
    
b = B(10, 20)
print(b)

B: 30


In [122]:
import numpy as np

def neg(A):
    A[A < 0] = 0
    return -1 * A

In [123]:
A = np.array([[1,-2,3],
                [-4,5,-6],
                [7,8,0]])
print(neg(A))

[[-1  0 -3]
 [ 0 -5  0]
 [-7 -8  0]]


# Exam 31/01/2024:

In [133]:
def new_update(D1,D2):
    ...

D1={1:10, 2:20}
D2={1:100, 3:30}

def remove_keys(keys, D):
    for key in keys:
        del D[key]

keys_to_remove = []
for key, value in D1.items():

    if key in D2.keys():
        keys_to_remove.append(key)

    else:
        D2[key] = value

remove_keys(keys_to_remove, D1)
remove_keys(keys_to_remove, D2)


new_update(D1,D2)
print(D1=={2: 20},D2=={2:20, 3: 30})


True True


Write a function printgen(G) that takes a generator G and prints the elements of G in reverse order.

In [135]:
def printgen(X):
    XL = list(X)
    XLI = XL[::-1]
    for x in XLI:
        print(x)

X = (i for i in range(4))
printgen(X)

3
2
1
0


In [206]:
def partition(L):
    n = len(L)
    for i in range(n):
        for j in range(0, n - i - 1):
            if L[j] > L[j + 1]:
                L[j], L[j + 1] = L[j + 1], L[j]


L=[10, 1, 11, 22, 3, 5, 23]

partition(L)
assert L[3]==10
assert all (L[i]<L[3] for i in range(3))
assert all (L[i]>L[3] for i in range(4,len(L)))


In [210]:
class A:
    def __init__(self, x):
        self.x = x

class B(A):
    def __init__(self, x, y):
        super().__init__(x)
        self.y = y

    def __str__(self):
        return f"B: {self.y * self.xx}" 
    
b= B(10, 20)
print(b)

B: 200


In [219]:
import numpy as np

def filter_ones(A,B):
    return A[B.T == 1]

A = np.array([[7,1,4], [2,5,4]])
B = np.array([[0,1], [1,0],[1,1]])

print(filter_ones(A,B))





[1 4 2 4]


array([1, 4, 2, 4])

# Exam 19/06/2024:

In [225]:
def my_update(D1, D2):
    
    for key, value in D2.items():
        if key not in D1.keys():
            D1[key] = value
        else:
            D1[key] = D2[key] + D1[key]


D1={1:'10',2:20}
D2={1:'100',3:30}

print(D1,D2)
my_update(D1,D2)
print(D1,D2)
print(D1=={1: '10010', 2: 20, 3: 30},D2=={1: '100', 3: 30})

{1: '10', 2: 20} {1: '100', 3: 30}
{1: '10010', 2: 20, 3: 30} {1: '100', 3: 30}
True True


In [231]:
class A(Exception): ...

class B(A):
    def __init__(self, b):
        self.b = b 
    
    def __str__(self):
        return str(self.b)
    
b = B(10)
print(b)

10


In [ ]:
def has_spicca(L: list) -> bool:
    return any([L[i - 1] < L[i] > L[i + 1] for i in range(1, len(L) - 1)])

def spicca(L: list) -> list:
    L_new = []
    for i in range(len(L)):
        if i == 0 or i == len(L) - 1:
            L_new.append(L[i])
        elif not (L[i - 1] < L[i] > L[i + 1]):
            L_new.append(L[i])

    if has_spicca(L_new):
        return spicca(L_new)

    return L_new

In [64]:
class Top:
    def __init__(self,s):
        if type(s)!=str:
            raise TypeError
        self.__st = s

    def get_str(self):
        return self.__st

class A(Top): 

    def __eq__(self, value):
        if isinstance(value, A):
            return self.get_str() == value.get_str()
        return False

class B(A):

    def __eq__(self, value):
        if isinstance(value, B):
            return self.get_str() == value.get_str()[::-1]
        return False
    
a1=A('pippo')
a2=A('pippo')
print(a1==a2)

b1=B('pippo')
b2=B('oppip')
print(b1==b2)

True
True


In [72]:
import numpy as np

def min_col(A):
    return np.min(A, axis=0)

A = np.array([[2,4,9],
              [3,2,1],
              [7,3,1]])
print(min_col(A))

[2 2 1]
