In [107]:
import numpy as np

def merge(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    b_reshaped = b.reshape(a.shape)
    return np.maximum(a, b_reshaped).astype(float)


In [40]:
import numpy as np

a = np.array([
    [0, 20, 4],
    [7, 1, 3]    
])
b = np.array([0, 1, 2, 3, 4, 5])


a.shape


(2, 3)

In [42]:
b.reshape(a.shape)

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
a.reshape(b.shape)

array([ 0, 20,  4,  7,  1,  3])

In [43]:
a, b

(array([[ 0, 20,  4],
        [ 7,  1,  3]]),
 array([0, 1, 2, 3, 4, 5]))

In [ ]:
b_reshaped = b.reshape(a.shape)
b_reshaped



In [45]:
merged_array = merge(a, b)
print(merged_array)


[[ 0. 20.  4.]
 [ 7.  4.  5.]]


In [58]:
import numpy as np

def demean(a: np.ndarray) -> np.ndarray:
    return a - np.mean(a, axis=0)

vector = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

print(demean(vector))


[[-4.5 -4.5 -4.5]
 [-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]
 [ 4.5  4.5  4.5]]


In [94]:
vector = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

mean_vector = np.mean(vector)
vector_minus_mean = vector - mean_vector
mean_vector, vector_minus_mean


(np.float64(6.5),
 array([[-5.5, -4.5, -3.5],
        [-2.5, -1.5, -0.5],
        [ 0.5,  1.5,  2.5],
        [ 3.5,  4.5,  5.5]]))

In [57]:
np.empty((3, 2))

array([[ 0., 20.],
       [ 4.,  7.],
       [ 4.,  5.]])

In [90]:
import numpy as np

def colsum(a: np.ndarray) -> np.ndarray:
    return np.array([np.sum(a[::, ::2]) ,np.sum(a[::, 1::2])])



In [92]:
vector = np.array([
    [2, 7, 8, 0],
    [3, 9, 3, 4],
    [4, 0, 1, 3],
])

print(colsum(vector))

[21 23]


In [72]:
y = np.arange(35).reshape(5,7) 
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [81]:
y[::, ::2], y[::, 1::2]

(array([[ 0,  2,  4,  6],
        [ 7,  9, 11, 13],
        [14, 16, 18, 20],
        [21, 23, 25, 27],
        [28, 30, 32, 34]]),
 array([[ 1,  3,  5],
        [ 8, 10, 12],
        [15, 17, 19],
        [22, 24, 26],
        [29, 31, 33]]))

In [88]:
a = np.sum(y[::, ::2])
b = np.sum(y[::, 1::2])

vec = np.array([a, b])
vec

array([340, 255])

In [99]:
import numpy as np

def count_common(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return np.sum( a == b)


In [100]:
a = np.array([
    [1, 3, 8],
    [4, 5, 2],
    [3, 2, 9],
])
b = np.array([
    [2, 3, 7],
    [4, 5, 9],
    [6, 6, 6],
])

print( count_common(a, b) )

3


In [151]:
import numpy as np

def foo(i: int, j: int) -> np.ndarray:
    return (i + j) % 2 != 0

def checkerboard(m: int) -> np.ndarray:
    return np.fromfunction(foo, (m, m)).astype(int)

print(checkerboard(10))


[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


In [102]:
vec = np.array([])

print(vec)

[]


In [106]:
m = 1

np.zeros((m, m)), np.ones((m, m))

(array([[0.]]), array([[1.]]))

In [113]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
G = (False if i % 2 == 0 else True for i in range(10))
a = np.fromiter(G, dtype=int)
a

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [143]:
def foo(i: int, j: int) -> bool:
    return (i + j) % 2 == 0

vec = np.fromfunction(foo, (3, 3))
vec


array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [147]:
def foo(i: int, j: int) -> np.ndarray:
    return (i + j) % 2 == 0

vec = np.fromfunction(foo, (3, 3)).astype(int)
vec


array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [152]:
import numpy as np


def zeroones(p: int, q: int):
    pass

p, q = 5, 5


def boarder(i, j):
    return 0



In [159]:
import numpy as np

def zero_arrays(p: int, q: int) -> np.ndarray:
    return np.zeros((p, q), dtype=float)

def sequence_numbers(inner_rows, inner_cols) -> np.ndarray:
    return np.arange(1, inner_rows * inner_cols + 1)

def zeroones(p, q) -> np.ndarray:
    
    arr = zero_arrays(p, q)
    inner_rows, inner_cols = p - 2, q - 2
    numbers = sequence_numbers(inner_rows, inner_cols)
    inner_array = numbers.reshape((inner_rows, inner_cols))
    arr[1:-1, 1:-1] = inner_array
    
    return arr


print(zeroones(5, 5))


[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 4. 5. 6. 0.]
 [0. 7. 8. 9. 0.]
 [0. 0. 0. 0. 0.]]


In [167]:
p, q = 5, 5

arr = np.zeros( shape=(p, q), dtype=float )

arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [166]:
inner_rows, inner_cols = p - 2, q - 2
inner_rows, inner_cols


(3, 3)

In [170]:
numbers = np.arange(start = 1, stop = inner_rows * inner_cols + 1)
numbers


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
inner_array = numbers.reshape((inner_rows, inner_cols))
inner_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [229]:
zero_array_ = np.zeros(shape=(2, 5), dtype=float)
zero_array_

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [226]:
arr_ = np.arange(1, 29).reshape(4, 7)
arr_

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28]])

In [232]:
arr_[1:-1, 1:-1] = zero_array_
arr_


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  0,  0,  0,  0,  0, 14],
       [15,  0,  0,  0,  0,  0, 21],
       [22, 23, 24, 25, 26, 27, 28]])

In [2]:
import numpy as np

def zerocolumns(a: np.ndarray) -> np.ndarray:
    return a[:, np.all(a != 0, axis=0)]


In [3]:
a = np.array([[1, 2, 0],
              [3, 1, 1],
              [3, 3, 0]])

print(zerocolumns(a))


[[1 2]
 [3 1]
 [3 3]]


In [4]:

a = np.array([
    [0, 2, 3,  5],
    [3, 0, 1,  5],
    [3, 3, 0,  5],
    [3, 3, 42, 0],
])

a

array([[ 0,  2,  3,  5],
       [ 3,  0,  1,  5],
       [ 3,  3,  0,  5],
       [ 3,  3, 42,  0]])

In [5]:
a = np.array([
    [1, 2, 0],
    [3, 1, 1],
    [3, 3, 0],
])


In [7]:
(a == 0)


array([[False, False,  True],
       [False, False, False],
       [False, False,  True]])

In [14]:
# 0 - column
# 1 - row
np.all(a != 0, axis=0)


array([ True,  True, False])

In [42]:
import numpy as np

def arraydistance(p: int, q: int) -> np.ndarray:
    return np.fromfunction(lambda i, j: np.sqrt(i**2 + j**2), (p, q))



print(arraydistance(4, 7))



[[0. 1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6. 7.]
 [2. 3. 4. 5. 6. 7. 8.]
 [3. 4. 5. 6. 7. 8. 9.]]


In [74]:
import numpy as np

def lowest(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return np.lcm.outer(a, b)



In [75]:
a = np.array([27,73,91,79,89,28,63,48,71]) #np.arange(0, 10)
b = np.array([7,7,8,9,4,6,2]) #np.arange(0, 5)

lowest(a, b)

array([[189, 189, 216,  27, 108,  54,  54],
       [511, 511, 584, 657, 292, 438, 146],
       [ 91,  91, 728, 819, 364, 546, 182],
       [553, 553, 632, 711, 316, 474, 158],
       [623, 623, 712, 801, 356, 534, 178],
       [ 28,  28,  56, 252,  28,  84,  28],
       [ 63,  63, 504,  63, 252, 126, 126],
       [336, 336,  48, 144,  48,  48,  48],
       [497, 497, 568, 639, 284, 426, 142]])

In [76]:
print(lowest(np.arange(0,10), np.arange(0,5)))


[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  2  6  4]
 [ 0  3  6  3 12]
 [ 0  4  4 12  4]
 [ 0  5 10 15 20]
 [ 0  6  6  6 12]
 [ 0  7 14 21 28]
 [ 0  8  8 24  8]
 [ 0  9 18  9 36]]


In [73]:
np.lcm.outer(a, b)

array([[189, 189, 216,  27, 108,  54,  54],
       [511, 511, 584, 657, 292, 438, 146],
       [ 91,  91, 728, 819, 364, 546, 182],
       [553, 553, 632, 711, 316, 474, 158],
       [623, 623, 712, 801, 356, 534, 178],
       [ 28,  28,  56, 252,  28,  84,  28],
       [ 63,  63, 504,  63, 252, 126, 126],
       [336, 336,  48, 144,  48,  48,  48],
       [497, 497, 568, 639, 284, 426, 142]])

In [101]:
import numpy as np

def element(a: np.ndarray, p: int):
    a_flatten = np.ndarray.flatten(a)
    possible_dimension = a_flatten.shape[0]
    return -1 if p >= possible_dimension or p < 0 else a_flatten[p]

    
print(element(np.array([[[4,3,6],[3,2,8]],[[1,5,7],[2,6,7]],[[3,6,7],[3,7,4]],[[4,2,7],[4,3,1]],[[5,3,5],[3,6,5]]]), 0))  #->  4
print(element(np.array([[[4,3,6],[3,2,8]],[[1,5,7],[2,6,7]],[[3,6,7],[3,7,4]],[[4,2,7],[4,3,1]],[[5,3,5],[3,6,5]]]), 5))  #->  8
print(element(np.array([[[4,3,6],[3,2,8]],[[1,5,7],[2,6,7]],[[3,6,7],[3,7,4]],[[4,2,7],[4,3,1]],[[5,3,5],[3,6,5]]]), 29)) #->  5
print(element(np.array([[[4,3,6],[3,2,8]],[[1,5,7],[2,6,7]],[[3,6,7],[3,7,4]],[[4,2,7],[4,3,1]],[[5,3,5],[3,6,5]]]), 30)) #-> -1

4
8
5
-1


In [94]:
q = np.array([[189, 189, 216,  27, 108,  54,  54],
       [511, 511, 584, 657, 292, 438, 146],
       [ 91,  91, 728, 819, 364, 546, 182],
       [553, 553, 632, 711, 316, 474, 158],
       [623, 623, 712, 801, 356, 534, 178],
       [ 28,  28,  56, 252,  28,  84,  28],
       [ 63,  63, 504,  63, 252, 126, 126],
       [336, 336,  48, 144,  48,  48,  48],
       [497, 497, 568, 639, 284, 426, 142]])

list(q.shape)

[9, 7]

In [96]:
q_ = np.ndarray.flatten(q)
q_.shape[0]

63

In [98]:
q_[9]

np.int64(584)

In [87]:
arr = np.arange(10).reshape(2, 5)
arr


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [92]:
arr = np.array([1, 2, 3, 4], ndmin=2)
arr.shape

(1, 4)

In [93]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [126]:
import numpy as np

def permute_array(m):
    arr = np.arange(m + 1)
    for i in range(0, m - 1, 2):
        arr[i], arr[i + 1] = arr[i + 1], arr[i]
    
    return arr


# Test with m = 5
m = 5
arr_perm = permute_array(m)
print(arr_perm)



[1 0 3 2 4 5]


In [102]:
import numpy as np

def exchangecolumns(a: np.ndarray) -> np.ndarray | None:
    rows, columns = a.shape
    if columns % 2 != 0:
        return None
    


In [111]:
a = np.arange(0,6).reshape(3,2)
rows, columns = a.shape

rows, columns

(3, 2)

In [114]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [116]:
a_T = a.T
a_T

array([[0, 2, 4],
       [1, 3, 5]])

In [121]:
import numpy as np

#create NumPy array
array = np.array([
    [1, 1, 2], 
    [3, 3, 7], 
    [4, 3, 1], 
    [9, 9, 5], 
    [6, 7, 7],
    [0, 0, 0],
])

#view NumPy array
print(array)



[[1 1 2]
 [3 3 7]
 [4 3 1]
 [9 9 5]
 [6 7 7]
 [0 0 0]]


In [118]:
#swap columns 1 and 3
array[:, [0, 2]] = array[:, [2, 0]]

#view updated NumPy array
print(array)


[[2 1 1]
 [7 3 3]
 [1 3 4]
 [5 9 9]
 [7 7 6]]


In [119]:
#swap rows 1 and 3
array[[0, 2], :] = array[[2, 0], :]

print(array)


[[1 3 4]
 [7 3 3]
 [2 1 1]
 [5 9 9]
 [7 7 6]]


In [122]:
import numpy as np

def permute_array(m):
    arr = np.arange(m + 1)
    idx_perm = np.arange(len(arr))
    temp = idx_perm[2:].copy()
    swap_len = (len(temp) // 2) * 2  # Ensure swap_len is even
    if swap_len > 0:
        temp_subarray = temp[:swap_len].reshape(-1, 2)
        temp_subarray = temp_subarray[:, ::-1]  # Swap elements in pairs
        temp[:swap_len] = temp_subarray.reshape(-1)
    idx_perm[2:] = temp
    arr_perm = arr[idx_perm]
    return arr_perm

m = 5
arr_perm = permute_array(m)
print("Permuted array:", arr_perm)


Permuted array: [0 1 3 2 5 4]


In [125]:
import numpy as np

def permute_array(m):
    # Create the array from 0 to m
    arr = np.arange(m + 1)
    
    # Swap adjacent pairs up to the second-to-last element
    for i in range(0, m - 1, 2):
        arr[i], arr[i + 1] = arr[i + 1], arr[i]
    
    return arr

# Test with m = 5
m = 5
arr_perm = permute_array(m)
print(arr_perm)



[1 0 3 2 4 5]


In [173]:
import numpy as np

def exchangecolumns(a: np.ndarray) -> np.ndarray:

    num_rows, num_cols = a.shape
    if num_cols % 2 != 0:
        return None

    perm = np.empty(num_cols, dtype=int)
    perm[0::2], perm[1::2] = np.arange(1, num_cols, 2), np.arange(0, num_cols, 2)
    #perm[1::2] = np.arange(0, num_cols, 2)

    return a[:, perm]


In [157]:
a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [158]:
num_rows, num_cols = a.shape
num_rows, num_cols

(5, 5)

In [166]:
num_cols = 8

In [167]:
np.arange(1, num_cols, 2)

array([1, 3, 5, 7])

In [169]:
perm = np.empty(num_cols, dtype=int)
print(perm)

perm[0::2] = np.arange(1, num_cols, 2)
print(perm)

perm[1::2] = np.arange(0, num_cols, 2)
print(perm)



[4607182418800017408 4611686018427387904 4613937818241073152
 4616189618054758400 4617315517961601024 4618441417868443648
 4619567317775286272 4620693217682128896]
[                  1 4611686018427387904                   3
 4616189618054758400                   5 4618441417868443648
                   7 4620693217682128896]
[1 0 3 2 5 4 7 6]


In [153]:
perm[0::2]

array([0, 0])

In [174]:
# Testing the function
print(exchangecolumns(np.arange(0, 6).reshape(3, 2)))
print(exchangecolumns(np.arange(0, 20).reshape(5, 4)))
print(exchangecolumns(np.arange(0., 12.).reshape(3, 4)))
print(exchangecolumns(np.arange(0, 25).reshape(5, 5)))  # Should return None
print(exchangecolumns(np.array([[3, 42, 5, 11, 44, 55], [7, 9, 4, 1, 3, 2]])))


[[1 0]
 [3 2]
 [5 4]]
[[ 1  0  3  2]
 [ 5  4  7  6]
 [ 9  8 11 10]
 [13 12 15 14]
 [17 16 19 18]]
[[ 1.  0.  3.  2.]
 [ 5.  4.  7.  6.]
 [ 9.  8. 11. 10.]]
None
[[42  3 11  5 55 44]
 [ 9  7  1  4  2  3]]


In [138]:
a = np.arange(0,20).reshape(5, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [130]:
# Check if the number of columns is even
a.shape[1]


2

In [133]:
perm = np.arange(a.shape[1])
perm

array([0, 1])

In [134]:
perm[::2], perm[1::2] = perm[1::2], perm[::2]
perm

array([1, 1])

In [135]:
import numpy as np

def exchangecolumns(a):
    # Check if the number of columns is even
    if a.shape[1] % 2 != 0:
        return None

    # Create a permutation array [1, 0, 3, 2, 5, 4, ...]
    perm = np.arange(a.shape[1])
    perm[::2], perm[1::2] = perm[1::2], perm[::2]

    # Apply the permutation to the columns
    return a[:, perm]

# Testing the function
print(exchangecolumns(np.arange(0, 6).reshape(3, 2)))
print(exchangecolumns(np.arange(0, 20).reshape(5, 4)))
print(exchangecolumns(np.arange(0., 12.).reshape(3, 4)))
print(exchangecolumns(np.arange(0, 25).reshape(5, 5)))  # Should return None
print(exchangecolumns(np.array([[3, 42, 5, 11, 44, 55], [7, 9, 4, 1, 3, 2]])))


[[1 1]
 [3 3]
 [5 5]]
[[ 1  1  3  3]
 [ 5  5  7  7]
 [ 9  9 11 11]
 [13 13 15 15]
 [17 17 19 19]]
[[ 1.  1.  3.  3.]
 [ 5.  5.  7.  7.]
 [ 9.  9. 11. 11.]]
None
[[42 42 11 11 55 55]
 [ 9  9  1  1  2  2]]


In [137]:
import numpy as np

def exchangecolumns(a: np.ndarray):
    """
    Swap adjacent columns in a 2D NumPy array.
    
    Parameters:
    a (np.ndarray): A 2D NumPy array.
    
    Returns:
    np.ndarray or None: The array with adjacent columns swapped, or None if the number of columns is odd.
    """
    # Check if the input is a 2D array
    if a.ndim != 2:
        raise ValueError("Input array must be 2-dimensional.")
    
    num_cols = a.shape[1]
    
    # If the number of columns is odd, return None
    if num_cols % 2 != 0:
        return None
    
    # Generate the permutation array
    # Example for num_cols=6: [1, 0, 3, 2, 5, 4]
    perm = np.empty(num_cols, dtype=int)
    perm[0::2] = np.arange(1, num_cols, 2)
    perm[1::2] = np.arange(0, num_cols, 2)
    
    # Alternatively, using reshape and swap:
    # perm = np.arange(num_cols).reshape(-1, 2)[:, [1, 0]].flatten()
    
    # Apply the permutation to the columns
    return a[:, perm]

# Testing the function with the provided examples

# Test 1
print("Test 1:")
arr1 = np.arange(0,6).reshape(3,2)
print("Original Array:\n", arr1)
print("Swapped Columns:\n", exchangecolumns(arr1))
print()

# Test 2
print("Test 2:")
arr2 = np.arange(0,20).reshape(5,4)
print("Original Array:\n", arr2)
print("Swapped Columns:\n", exchangecolumns(arr2))
print()

# Test 3
print("Test 3:")
arr3 = np.arange(0.,12.).reshape(3,4)
print("Original Array:\n", arr3)
print("Swapped Columns:\n", exchangecolumns(arr3))
print()

# Test 4
print("Test 4:")
arr4 = np.arange(0,25).reshape(5,5)
print("Original Array:\n", arr4)
print("Swapped Columns:\n", exchangecolumns(arr4))
print()

# Test 5
print("Test 5:")
arr5 = np.array([[3,42,5,11,44,55],
                 [7,9,4,1,3,2]])
print("Original Array:\n", arr5)
print("Swapped Columns:\n", exchangecolumns(arr5))


Test 1:
Original Array:
 [[0 1]
 [2 3]
 [4 5]]
Swapped Columns:
 [[1 0]
 [3 2]
 [5 4]]

Test 2:
Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Swapped Columns:
 [[ 1  0  3  2]
 [ 5  4  7  6]
 [ 9  8 11 10]
 [13 12 15 14]
 [17 16 19 18]]

Test 3:
Original Array:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
Swapped Columns:
 [[ 1.  0.  3.  2.]
 [ 5.  4.  7.  6.]
 [ 9.  8. 11. 10.]]

Test 4:
Original Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Swapped Columns:
 None

Test 5:
Original Array:
 [[ 3 42  5 11 44 55]
 [ 7  9  4  1  3  2]]
Swapped Columns:
 [[42  3 11  5 55 44]
 [ 9  7  1  4  2  3]]
