In [1]:
#do not insert print
A=[10,-20,30, -1]

def f():
    A=10
    #commands here (only inside the body of the function)
    #do not use the global command
    
    
    #end of commands for the body of f()

#other possible commands here, outside the def of f()
#you cannot use commands which modify A or its binding


#do not modify from here
f()

#do not insert print
A = [10, -20, 30, -1]

def f():
    A = [x for x in globals()['A'] if x >= 0]  # Filter only non-negative elements
    # This redefines A within the function scope without using global

#other possible commands here, outside the def of f()
A = [x for x in A if x >= 0]  # Filter non-negative elements of A globally

#do not modify from here
f()


In [26]:
class A:

    def __init__(self: "A", xx: float) -> None: 
        self.__x = xx

    def get(self: "A") -> float: 
        return self.__x


class B(A):
    pass

class C(B):

    def get(self: "C") -> float:
        return super().get()
    
    def __add__(self: "C", other: "C") -> str:
        return f"C: {self.get() + other.get()}"



print(C(10) + C(20))


C: 30


In [54]:

class Seq:

    def __init__(self, seque) -> None:
        self.__s = seque

    def get_prefs(self: "Seq") -> list:
        ss_unique = []
        for i in range(len(self.__s)):
            
            if i == 0:
                ss_unique.append(self.__s[i])
                continue

            if self.__s[i] != ss_unique[-1]:
                ss_unique.append(self.__s[i])
                continue
        
        return ss_unique
    
def prefs(S: Seq) -> int:
    return len(S.get_prefs())

print(prefs(Seq('sottoolii')))

6


In [ ]:
ss = "sottoolii"

ss_unique = []
for i in range(len(ss)):
    
    if i == 0:
        ss_unique.append(ss[i])
        continue

    if ss[i] != ss_unique[-1]:
        ss_unique.append(ss[i])
        continue

ss_unique

[FLAG 01]
  ss_unique = ['s']
[FLAG 02]
  ss[i] = o | ss_unique[-1] = s 
  ss_unique = ['s', 'o']
[FLAG 02]
  ss[i] = t | ss_unique[-1] = o 
  ss_unique = ['s', 'o', 't']
[FLAG 02]
  ss[i] = o | ss_unique[-1] = t 
  ss_unique = ['s', 'o', 't', 'o']
[FLAG 02]
  ss[i] = l | ss_unique[-1] = o 
  ss_unique = ['s', 'o', 't', 'o', 'l']
[FLAG 02]
  ss[i] = i | ss_unique[-1] = l 
  ss_unique = ['s', 'o', 't', 'o', 'l', 'i']


['s', 'o', 't', 'o', 'l', 'i']

In [57]:
class Top:

    def __init__(self, c: int) -> None: #DO NOT modify __init__
        if type(c) != int:
            raise TypeError
        
        self.__n = c

    def get(self) -> int:
        return self.__n


class A(Top):
    #complete here the def of A, as needed
    def __init__(self: "A", c: int) -> None:
        super().__init__(c)

    def __eq__(self: "A", other: "A") -> bool:
        return self.get() == other.get()

class B(A):
    #complete here the def of B, as needed
    def __init__(self: "B", c: int) -> None:
        super().__init__(c)

    def __eq__(self: "B", other: "B") -> bool:
        return abs(self.get()) == abs(other.get())
    
# DO NOT MODIFY THE FOLLOWING
a1=A(1)
a2=A(-1)

print(a1==a2)

b1=B(1)
b2=B(-1)

print(b1==b2)

False
True


In [80]:
#do not insert print or tests
import numpy as np

def select(a: np.ndarray, b: np.ndarray, n: int):
    # BEGIN STUDENT CODE HERE
    a_flatten, b_flatten = a.flatten(), b.flatten()
    if len(a_flatten) != len(b_flatten):
        return a
    
    return a_flatten[b_flatten < n]
    # END STUDEND CODE HERE
    

n = 6
A = np.array([
    [0, 4, 3, 7],
    [3, 2, 4, 4],
    [6, 6, 6, 2],
])

B = np.array([1, 2, 9, 5, 2, 9, 6, 7, 7, 2, 3, 2])


In [73]:
a_flatten, b_flatten = A.flatten(), B.flatten()
a_flatten, b_flatten

(array([0, 4, 3, 7, 3, 2, 4, 4, 6, 6, 6, 2]),
 array([1, 2, 9, 5, 2, 9, 6, 7, 7, 2, 3, 2]))

In [74]:
b = b_flatten[b_flatten < n]
b, b_flatten

(array([1, 2, 5, 2, 2, 3, 2]), array([1, 2, 9, 5, 2, 9, 6, 7, 7, 2, 3, 2]))

In [77]:
a_flatten[b_flatten < n]

array([0, 4, 7, 3, 6, 6, 2])

In [81]:
print(select(np.array([[0, 4, 3, 7],
                       [3, 2, 4, 4],
                       [6, 6, 6, 2]]),
             np.array([1, 2, 9, 5, 2, 9, 6, 7, 7, 2, 3, 2]),
             6))

[0 4 7 3 6 6 2]
