In [57]:
def my_update(D1: dict, D2: dict) -> None:
    for key, value in D1.items():
        if key in list(D2.keys()):
            D1[key] = D2[key] + D1[key]
    
    for key, value in D2.items():
        if key not in list(D1.keys()):
            D1[key] = value


D1={1:'10', 2:20}
D2={1:'100', 3:30}
my_update(D1,D2)
print(D1=={1: '10010', 2: 20, 3: 30},D2=={1: '100', 3: 30})

True True


In [58]:
class A(Exception):
    pass

class B(A):
    def __init__(self, foo):
        self.foo = foo

    def __str__(self):
        return str(self.foo)

foo = 10  


In [103]:
L_new = []
L = [1, 3, 4, 0, 9, 6, 8, 7, 2, 999]

L_size = len(L)
GREEN = "\033[32;m"
RED = "\033[31;m"
RESET = "\033[0;m"

position = 0
while position < L_size - 1 :

    if position == 0:
        x_i, x_i_plus_1 = L[position], L[position + 1]
        print(f"[FIRST]: {x_i}")
        print(f"\t - X[{position}]: {x_i} | X[{position +1 }]: {x_i_plus_1}")
        print(f"\t - X[{position}]: {x_i} < X[{position +1 }]: {x_i_plus_1} ? {GREEN if x_i < x_i_plus_1 else RED}{x_i < x_i_plus_1}{RESET}")
        L_new.append(x_i)

    elif 0 < position < L_size - 2:
        x_i_minus_1, x_i, x_i_plus_1 = L[position - 1], L[position], L[position + 1]
        is_local_maxima = (x_i_minus_1 < x_i) and (x_i > x_i_plus_1)
        print(f"[REGULAR]: {x_i}")
        print(f"\t - X[{position - 1}]: {x_i_minus_1} | X[{position}]: {x_i} | X[{position + 1}]: {x_i_plus_1}")
        print(f"\t - X[{position - 1}]: {x_i_minus_1} < X[{position}]: {x_i} > X[{position + 1}]: {x_i_plus_1} ? {GREEN if is_local_maxima else RED}{is_local_maxima}{RESET}")
        if not is_local_maxima:
            L_new.append(x_i)
    
    elif position == L_size - 2:
        x_i, x_i_plus_1 = L[position], L[position + 1]
        print(f"[LAST]: {x_i}")
        is_local_maxima = x_i < x_i_plus_1
        print(f"\t - X[{position}]: {x_i} | X[{position + 1}]: {x_i_plus_1}")
        print(f"\t - X[{position}]: {x_i} < X[{position + 1}] ? {GREEN if is_local_maxima else RED}{is_local_maxima}{RESET}")
        L_new.append(x_i)

    position += 1


[FIRST]: 1
	 - X[0]: 1 | X[1]: 3
	 - X[0]: 1 < X[1]: 3 ? True
[REGULAR]: 3
	 - X[0]: 1 | X[1]: 3 | X[2]: 4
	 - X[0]: 1 < X[1]: 3 > X[2]: 4 ? False
[REGULAR]: 4
	 - X[1]: 3 | X[2]: 4 | X[3]: 0
	 - X[1]: 3 < X[2]: 4 > X[3]: 0 ? True
[REGULAR]: 0
	 - X[2]: 4 | X[3]: 0 | X[4]: 9
	 - X[2]: 4 < X[3]: 0 > X[4]: 9 ? False
[REGULAR]: 9
	 - X[3]: 0 | X[4]: 9 | X[5]: 6
	 - X[3]: 0 < X[4]: 9 > X[5]: 6 ? True
[REGULAR]: 6
	 - X[4]: 9 | X[5]: 6 | X[6]: 8
	 - X[4]: 9 < X[5]: 6 > X[6]: 8 ? False
[REGULAR]: 8
	 - X[5]: 6 | X[6]: 8 | X[7]: 7
	 - X[5]: 6 < X[6]: 8 > X[7]: 7 ? True
[REGULAR]: 7
	 - X[6]: 8 | X[7]: 7 | X[8]: 2
	 - X[6]: 8 < X[7]: 7 > X[8]: 2 ? False
[LAST]: 2
	 - X[8]: 2 | X[9]: 999
	 - X[8]: 2 < X[9] ? True


In [126]:
L_new = []
L = [1, 3, 4, 0, 9, 6, 8, 7, 2, 999]

L_size = len(L)
GREEN = "\033[32;m"
RED = "\033[31;m"
RESET = "\033[0;m"

position = 0
while position < L_size :

    if position == 0:
        x_i, x_i_plus_1 = L[position], L[position + 1]
        print(f"[FIRST]: {position}/{L_size - 1}")
        print(f"\t - X[{position}]: {x_i} | X[{position +1 }]: {x_i_plus_1}")
        print(f"\t - X[{position}]: {x_i} < X[{position +1 }]: {x_i_plus_1} ? {GREEN if x_i < x_i_plus_1 else RED}{x_i < x_i_plus_1}{RESET}")
        L_new.append(x_i)

    elif 0 < position < L_size and position < L_size - 1:
        x_i_minus_1, x_i, x_i_plus_1 = L[position - 1], L[position], L[position + 1]
        is_local_maxima = (x_i_minus_1 < x_i) and (x_i > x_i_plus_1)
        print(f"[REGULAR]: {position}/{L_size - 1}")
        print(f"\t - X[{position - 1}]: {x_i_minus_1} | X[{position}]: {x_i} | X[{position + 1}]: {x_i_plus_1}")
        print(f"\t - X[{position - 1}]: {x_i_minus_1} < X[{position}]: {x_i} > X[{position + 1}]: {x_i_plus_1} ? {GREEN if is_local_maxima else RED}{is_local_maxima}{RESET}")
        if not is_local_maxima:
            L_new.append(x_i)

    else:
        x_i_minus_1, x_i = L[position - 1], L[position]
        print(f"[LAST]: {position}/{L_size - 1}")
        is_local_maxima = (x_i_minus_1 < x_i)
        print(f"\t - X[{position - 1}]: {x_i_minus_1} | X[{position}]: {x_i}")
        print(f"\t - X[{position - 1}]: {x_i_minus_1} < X[{position}]: {x_i}: {x_i_plus_1} ? {GREEN if is_local_maxima else RED}{is_local_maxima}{RESET}")
        break

    position += 1


[FIRST]: 0/9
	 - X[0]: 1 | X[1]: 3
	 - X[0]: 1 < X[1]: 3 ? True
[REGULAR]: 1/9
	 - X[0]: 1 | X[1]: 3 | X[2]: 4
	 - X[0]: 1 < X[1]: 3 > X[2]: 4 ? False
[REGULAR]: 2/9
	 - X[1]: 3 | X[2]: 4 | X[3]: 0
	 - X[1]: 3 < X[2]: 4 > X[3]: 0 ? True
[REGULAR]: 3/9
	 - X[2]: 4 | X[3]: 0 | X[4]: 9
	 - X[2]: 4 < X[3]: 0 > X[4]: 9 ? False
[REGULAR]: 4/9
	 - X[3]: 0 | X[4]: 9 | X[5]: 6
	 - X[3]: 0 < X[4]: 9 > X[5]: 6 ? True
[REGULAR]: 5/9
	 - X[4]: 9 | X[5]: 6 | X[6]: 8
	 - X[4]: 9 < X[5]: 6 > X[6]: 8 ? False
[REGULAR]: 6/9
	 - X[5]: 6 | X[6]: 8 | X[7]: 7
	 - X[5]: 6 < X[6]: 8 > X[7]: 7 ? True
[REGULAR]: 7/9
	 - X[6]: 8 | X[7]: 7 | X[8]: 2
	 - X[6]: 8 < X[7]: 7 > X[8]: 2 ? False
[REGULAR]: 8/9
	 - X[7]: 7 | X[8]: 2 | X[9]: 999
	 - X[7]: 7 < X[8]: 2 > X[9]: 999 ? False
[LAST]: 9/9
	 - X[8]: 2 | X[9]: 999
	 - X[8]: 2 < X[9]: 999: 999 ? True


In [154]:
def has_spicca(L: list) -> bool:
    return any([L[i - 1] < L[i] > L[i + 1] for i in range(1, len(L) - 1)])

def spicca(L: list) -> list:

    position, L_new, L_size = 0, [], len(L)

    while position < L_size:
        
        if position == 0:
            L_new.append(L[position])

        elif 0 < position < L_size and position < L_size - 1:
            x_i_minus_1, x_i, x_i_plus_1 = L[position - 1], L[position], L[position + 1]
            is_local_maxima = (x_i_minus_1 < x_i) and (x_i > x_i_plus_1)
            if not is_local_maxima:
                L_new.append(x_i)
            
        else:
            L_new.append(L[position])

        position += 1

    if has_spicca(L_new):
        return spicca(L_new)

    return L_new

L = [1, 3, 4, 0, 9, 6, 8, 7, 2]
l = [1, 2, 3]
spicca(l)

[1, 2, 3]

In [136]:
def has_spicca(L: list) -> list:

    position,  L_size= 0, len(L)

    while position < L_size:
        
        if position == 0:
            pass

        elif 0 < position < L_size and position < L_size - 1:
            x_i_minus_1, x_i, x_i_plus_1 = L[position - 1], L[position], L[position + 1]
            is_local_maxima = (x_i_minus_1 < x_i) and (x_i > x_i_plus_1)
            if is_local_maxima:
                return True
            
        else:
            pass

        position += 1

    return False

L = [1, 3, 4, 0, 9, 6, 8, 7, 2, 999]
l = [1, 2, 3]
has_spicca(l)

False

In [144]:
def has_spicca(L: list) -> bool:
    for i in range(1, len(L) - 1):
        if L[i - 1] < L[i] > L[i + 1]:
            return True
    return False

L = [1, 3, 4, 0, 9, 6, 8, 7, 2, 999]
l = [1, 2, 3]
print(has_spicca(L))
print(has_spicca(l))


True
False


In [149]:
def has_spicca(L: list) -> bool:
    return any([L[i - 1] < L[i] > L[i + 1] for i in range(1, len(L) - 1)])

L = [1, 3, 4, 0, 9, 6, 8, 7, 2, 999]
l = [1, 2, 3]
l2 = [3, 2, 1]
l3 = [3, 2, 3]
l4 = [3, 4, 3]

print(has_spicca(L))
print(has_spicca(l))
print(has_spicca(l2))
print(has_spicca(l3))
print(has_spicca(l4))


True
False
False
False
True


In [ ]:
def has_spicca(L: list) -> bool:
    for i in range(1, len(L) - 1):
        if L[i - 1] < L[i] > L[i + 1]:
            return True
    return False

L = [1, 3, 4, 0, 9, 6, 8, 7, 2, 999]
l = [1, 2, 3]
print(has_spicca(L))
print(has_spicca(l))


In [163]:
def has_spicca(L: list) -> bool:
    return any([L[i - 1] < L[i] > L[i + 1] for i in range(1, len(L) - 1)])

def spicca(L: list) -> list:
    L_new = []
    for i in range(len(L)):
        if i == 0 or i == len(L) - 1:
            L_new.append(L[i])
        elif not (L[i - 1] < L[i] > L[i + 1]):
            L_new.append(L[i])

    if has_spicca(L_new):
        return spicca(L_new)

    return L_new

L = [1, 3, 4, 0, 9, 6, 8, 7, 2, 999]
l = [1, 2, 3]
l2 = [3, 2, 1]
l3 = [3, 2, 3]
l4 = [3, 4, 3]

print(spicca(L))
print(spicca(l))
print(spicca(l2))
print(spicca(l3))
print(spicca(l4))

[1, 0, 2, 999]
[1, 2, 3]
[3, 2, 1]
[3, 2, 3]
[3, 3]


In [166]:

class Top:
    def __init__(self, s: str) -> None:
        if type(s) != str:
            raise TypeError
        self.__st = s

    def get_st(self) -> str:
        return self.__st

class A(Top):
    # complete the definition of A if needed
    # you cannot redefine __init__
    def __eq__(self, value: object) -> bool:
        if isinstance(value, A):
            return self.get_st() == value.get_st()
        return False

class B(A):
    # complete the definition of B if needed
    # you cannot redefine __init__
    def __eq__(self, value: object) -> bool:
        if isinstance(value, B):
            return self.get_st() == value.get_st()[::-1]
        return False
    
a1 = A("a")
a2 = A("a")
a1 == a2

True

In [179]:
import numpy as np

def min_col(A) -> np.ndarray:
    return np.min(A, axis=0)

print(min_col(A))


[2 2 1]


In [176]:
A = np.array([[2,4,9],
              [3,2,1],
              [7,3,1]])
A.transpose()

array([[2, 3, 7],
       [4, 2, 3],
       [9, 1, 1]])

In [170]:
for line in A:
    print(line)

[2 4 9]
[3 2 1]
[7 3 1]


In [177]:
np.transpose(A)


array([[2, 3, 7],
       [4, 2, 3],
       [9, 1, 1]])

In [181]:
def spicca(L):
    i=1
    while i<len(L)-1:
        if L[i-1]<L[i]>L[i+1]:
            del L[i]
            #now check if a new peak has been created on i-1
            if i>1: #if i is 1 and it was a peak, we don't have to check on 0
                i-=1 
        else:
            i+=1
    return L


L=[1,3,4,0,9,6,8,7,2]
print(spicca(L))
print(spicca([]))
print(spicca([1]))
print(spicca([1,3]))
print(spicca([1,2,3]))
print(spicca([1,3,1]))
print(spicca([1,2,3,4,5,6,7,-1]))
print(spicca([7,6,5,4,3,2,3,-1]))

[1, 0, 2]
[]
[1]
[1, 3]
[1, 2, 3]
[1, 1]
[1, -1]
[7, 6, 5, 4, 3, 2, -1]


In [ ]:
def my_update(D1,D2):
    for k in D2:
        if k in D1:
            D1[k]=D2[k]+D1[k]
        else:
            D1[k]=D2[k]

'''
D1={1:'10',2:20}
D2={1:'100',3:30}
my_update(D1,D2)
print(D1=={1: '10010', 2: 20, 3: 30},D2=={1: '100', 3: 30})

D1={1:10,2:20}
D2={3:30,4:40}
id1=id(D1)
id2=id(D2)
my_update(D1,D2)
print(D1=={1: 10, 2: 20, 3: 30,4:40},D2=={3:30,4:40},id1==id(D1),id2==id(D2))

D1={1:10,2:20}
D2={1:100,2:200}
id1=id(D1)
id2=id(D2)
my_update(D1,D2)
print(D1=={1: 110, 2: 220},D2=={1:10,2:20},id1==id(D1),id2==id(D2))

D1={1:10,2:20}
D2={}
id1=id(D1)
id2=id(D2)
my_update(D1,D2)
print(D1=={1:10,2:20},D2=={},id1==id(D1),id2==id(D2))

D1={}
D2={1:10,2:20}
id1=id(D1)
id2=id(D2)
my_update(D1,D2)
print(D1=={1:10,2:20},D2=={1:10,2:20},id1==id(D1),id2==id(D2))

D1={1:'10',2:'20'}
D2={1:'100',2:'200'}
id1=id(D1)
id2=id(D2)
my_update(D1,D2)
print(D1=={1: '10010', 2: '20020'},D2=={1: '100', 2: '200'},id1==id(D1),id2==id(D2))
'''

class A(Exception):
    pass
class B(A):
    pass


def spicca(L):
    i=1
    while i<len(L)-1:
        if L[i-1]<L[i]>L[i+1]:
            del L[i]
            #now check if a new peak has been created on i-1
            if i>1: #if i is 1 and it was a peak, we don't have to check on 0
                i-=1 
        else:
            i+=1
    return L


# L=[1,3,4,0,9,6,8,7,2]
# print(spicca(L))
# print(spicca([]))
# print(spicca([1]))
# print(spicca([1,3]))
# print(spicca([1,2,3]))
# print(spicca([1,3,1]))
# print(spicca([1,2,3,4,5,6,7,-1]))
# print(spicca([7,6,5,4,3,2,3,-1]))


class Top:
    def __init__(self,s):
        if type(s)!=str:
            raise TypeError
        self.__st=s
    #completare la def di Top se necessario
    def get(self):
        return self.__st
class A(Top):
    #completare la def di A se necessario
    #NON si può definire il metodo __init__
    def __eq__(self, other):
        return self.get()==other.get()
    
class B(A):
    #completare la def di B se necessario
    #NON si può definire il metodo __init__
    def __eq__(self,other): 
        return self.get()==other.get()[::-1]


import numpy as np

def min_col(A):
    return np.min(A, axis=0)

    
"""
#test 0
A = np.array([[2,4,9],
              [3,2,1],
              [7,3,1]])
print(min_col(A))

#test 1
A = np.array([[11,12,-13],
              [5,-6,7],
              [-8,9,10]])
print(min_col(A))

#test 2
A = np.array([[2,2,2],
              [2,2,2]])
print(min_col(A))

#test 2
A = np.array([[2],
              [0],
              [1],
              [4]])
print(min_col(A))
"""
