In [65]:
D1={ 1:10, 2:20}
D2={ 1:100, 3:30}

def change_values(D1: dict, D2: dict, key) -> None:
    D2[key], D1[key] = D1[key], D2[key]

def my_update(D1: dict, D2: dict) -> None:
    for key, value in D2.items():
        if key not in list(D1.keys()):
            D1[key] = value
        else:
            change_values(D1, D2, key)

D1={1:10,2:20}
D2={1:100,3:30}
my_update(D1,D2)
D1, D2
print(D1=={1: 100, 2: 20, 3: 30},D2=={1: 10, 3: 30})

True True


In [58]:
def change_values(D1: dict, D2: dict, key) -> None:
    D2[key], D1[key] = D1[key], D2[key]

def my_update(D1: dict, D2: dict) -> None:
    D1_keys, D2_keys = list(D1.keys()), list(D2.keys())

    d1_key, d2_key = D1_keys.pop(), D2_keys.pop()

    while len(D2_keys) > 0 or len(D1_keys) > 0:

        if d2_key != d1_key:
            D1.update({d2_key : D2[d2_key]})

        elif d2_key == d1_key:
            change_values(D1, D2, d1_key)

        d1_key, d2_key = D1_keys.pop(), D2_keys.pop()


D1={1:10,2:20}
D2={1:100,3:30}
my_update(D1,D2)
D1, D2
# print(D1=={1: 100, 2: 20, 3: 30},D2=={1: 10, 3: 30})

({1: 10, 2: 20, 3: 30}, {1: 100, 3: 30})

In [61]:
def change_values(D1: dict, D2: dict, key):
    D2[key], D1[key] = D1[key], D2[key]

def my_update(D1: dict, D2: dict):
    D1_keys, D2_keys = list(D1.keys()), list(D2.keys())

    d1_key, d2_key = D1_keys.pop(), D2_keys.pop()

    while len(D2_keys) > 0 or len(D1_keys) > 0:
        key_teste = []

        if d1_key in key_teste or d2_key in key_teste:
            continue

        if d2_key != d1_key:
            D1.update({d2_key : D2[d2_key]})
            key_teste.extend([d1_key, d2_key])

        elif d2_key == d1_key:
            change_values(D1, D2, d1_key)
            key_teste.append(d1_key)

        d1_key, d2_key = D1_keys.pop(), D2_keys.pop()
        
D1={1:10,2:20}
D2={1:100,3:30}
my_update(D1,D2)
D1, D2

({1: 10, 2: 20, 3: 30}, {1: 100, 3: 30})

In [59]:

def change_values(D1: dict, D2: dict, key):
    D2[key], D1[key] = D1[key], D2[key]

def my_update(D1: dict, D2: dict):
    D1_keys, D2_keys = list(D1.keys()), list(D2.keys())

    d1_key, d2_key = D1_keys.pop(), D2_keys.pop()

    while len(D2_keys) > 0 or len(D1_keys) > 0:
        key_teste = []

        if d1_key in key_teste or d2_key in key_teste:
            continue

        if d2_key != d1_key:
            D1.update({d2_key : D2[d2_key]})
            key_teste.extend([d1_key, d2_key])

        elif d2_key == d1_key:
            change_values(D1, D2, d1_key)
            key_teste.append(d1_key)

        d1_key, d2_key = D1_keys.pop(), D2_keys.pop()



D1={1:10,  2:20}
D2={1:100, 3:30}

D1_keys = list(D1.keys())
D2_keys = list(D2.keys())

print(f"D1 = {D1}")
print(f"D2 = {D2}")
print("-" * 50)

d1_key = D1_keys.pop()
d2_key = D2_keys.pop()
while len(D2_keys) > 0 or len(D1_keys) > 0:

    if d2_key != d1_key:
        D1.update({d2_key : D2[d2_key]})

    elif d2_key == d1_key:
        change_values(D1, D2, d1_key)

    d1_key = D1_keys.pop()
    d2_key = D2_keys.pop()




D1, D2, D1_keys, D2_keys

D1 = {1: 10, 2: 20}
D2 = {1: 100, 3: 30}
--------------------------------------------------


({1: 10, 2: 20, 3: 30}, {1: 100, 3: 30}, [], [])

In [56]:
from typing import Dict

def my_update(D1: Dict[str, int], D2: Dict[str, int]):
    if D1.keys() == D2.keys():
        D1.update(D2)


D1={1:10,  2:20}
D2={1:100, 3:30}

D1_keys = list(D1.keys())
D2_keys = list(D2.keys())

print(f"D1 = {D1}")
print(f"D2 = {D2}")
print("-" * 50)

for d2_key in D2_keys:
    
    
    for d1_key in D1_keys:

        print(f"Comparing: {d2_key} with {d1_key}")
        print(f"=> D1 Before = {D1}")
        print(f"=> D2 Before = {D2}")

        if d2_key != d1_key:
            print(f"\n - Different: d2: {d2_key} and d1: {d1_key}")
            D1.update({d2_key : D2[d2_key]})

        elif d2_key == d1_key:
            
            key = d1_key
            print(f"\n - Same key: {key}")
            d1_value, d2_value = D1[key], D2[key]

            D1.update({key : d2_value})
            D2.update({key : d1_value})



        print(f"=> D1 After = {D1}")
        print(f"=> D2 After = {D2}")

        print("-" * 50)

    print("=" * 50)

D1, D2, D1_keys, D2_keys

D1 = {1: 10, 2: 20}
D2 = {1: 100, 3: 30}
--------------------------------------------------
Comparing: 1 with 1
=> D1 Before = {1: 10, 2: 20}
=> D2 Before = {1: 100, 3: 30}

 - Same key: 1
=> D1 After = {1: 100, 2: 20}
=> D2 After = {1: 10, 3: 30}
--------------------------------------------------
Comparing: 1 with 2
=> D1 Before = {1: 100, 2: 20}
=> D2 Before = {1: 10, 3: 30}

 - Different: d2: 1 and d1: 2
=> D1 After = {1: 10, 2: 20}
=> D2 After = {1: 10, 3: 30}
--------------------------------------------------
Comparing: 3 with 1
=> D1 Before = {1: 10, 2: 20}
=> D2 Before = {1: 10, 3: 30}

 - Different: d2: 3 and d1: 1
=> D1 After = {1: 10, 2: 20, 3: 30}
=> D2 After = {1: 10, 3: 30}
--------------------------------------------------
Comparing: 3 with 2
=> D1 Before = {1: 10, 2: 20, 3: 30}
=> D2 Before = {1: 10, 3: 30}

 - Different: d2: 3 and d1: 2
=> D1 After = {1: 10, 2: 20, 3: 30}
=> D2 After = {1: 10, 3: 30}
--------------------------------------------------


({1: 10, 2: 20, 3: 30}, {1: 10, 3: 30}, [1, 2], [1, 3])

In [53]:
def change_values(D1: dict, D2: dict, key):
    ...

key = 1

D1={1 : 10,  2 : 20}
D2={1 : 100, 3 : 30}

D1, D2

d1_value, d2_value = D1[key], D2[key]

D1, D2, d1_value, d2_value
D1[key], D2[key] = d2_value, d1_value

D1, D2

({1: 100, 2: 20}, {1: 10, 3: 30})

In [54]:
def change_values(D1: dict, D2: dict, key):
    D2[key], D1[key] = D1[key], D2[key]

key = 1

D1={1 : 10,  2 : 20}
D2={1 : 100, 3 : 30}

D1, D2

D2[key], D1[key] = D1[key], D2[key]


D1, D2

({1: 100, 2: 20}, {1: 10, 3: 30})

In [5]:

def _printgen(G):
    try: 
        while G:
            print(next(G))
    except StopIteration:
        pass

def printgen(G):
    elements = list(G)
    for element in elements:
        print(element)
    for element in elements:
        print(element)

X = (i for i in range(4))
printgen(X)

0
1
2
3
0
1
2
3


In [ ]:

def _printgen(G):
    try: 
        while G:
            print(next(G))
    except StopIteration:
        pass

def printgen(G):
    X = [G, G]
    for x in X:
        _printgen(x)

X=(i for i in range(4))

printgen(X)

In [36]:

def merge(L1: list, L2: list):
    l1, l2 = L1.pop(0), L2.pop(0)
    while len(L1) > 0 and len(L2) > 0:

        if l1 < l2:
            L3.append(l1)
            l1 = L1.pop(0)
        else:
            L3.append(l2)
            l2 = L2.pop(0)
        
    L3.extend(L1 or L2)
    return L3

L3 = []
L1, L2 = [1, 3, 5], [0, 2, 4, 6, 8, 10]

while len(L1) != 0 or len(L2) != 0:
    
    l1, l2 = L1.pop(0), L2.pop(0)
    print(f"L3 = {L3} | L1 = {L1} | L2 = {L2}\n")
    print(f"[{len(L1) != 0 or len(L2) != 0}] l1 = {l1} | l2 = {l2}")

    if l1 < l2:
        L3.append(l1)
        l1 = L1.pop(0)
    else:
        L3.append(l2)
        l2 = L2.pop(0)

    
L3.extend(L1 or L2)

L3




L3 = [] | L1 = [3, 5] | L2 = [2, 4, 6, 8, 10]

[True] l1 = 1 | l2 = 0
L3 = [0] | L1 = [5] | L2 = [6, 8, 10]

[True] l1 = 3 | l2 = 4


IndexError: pop from empty list

In [39]:
L3 = []
L1, L2 = [1, 3, 5], [0, 2, 4, 6, 8, 10]

for l1_i in range(len(L1)):
    for l2_i in range(len(L2)):
        if L1[l1_i] < L2[l2_i]:
            if L1[l1_i] not in L3:
                L3.append(L1[l1_i])
            

3

In [52]:
# L1, L2 = [1, 3, 5], [0, 2, 4, 6, 8, 10]
# L3 = L1 + L2

def merge(L1: list, L2: list) -> list:
    L = []
    L3 = L1 + L2
    for _ in range(len(L3)):
        menor = min(L3)
        index = L3.index(menor)
        value = L3.pop(index)
        L.append(value)

    return L

print(merge([1,3,5], [0,2,4,6,8,10]))

[0, 1, 2, 3, 4, 5, 6, 8, 10]


In [26]:
def merge(L1: list, L2: list) -> list:
    L3 = []
    l1, l2 = L1.pop(0), L2.pop(0)
    while len(L1) > 0 and len(L2) > 0:

        if l1 < l2:
            L3.append(l1)
            l1 = L1.pop(0)
        else:
            L3.append(l2)
            l2 = L2.pop(0)
        
    L3.extend(L1 or L2)
    return L3

print(merge([1,3,5], [0,2,4,6,8,10]))


[0, 1, 2, 3, 6, 8, 10]


In [53]:
class A:
   def __init__(self, x: float) -> None:
     self.xx = x

class B(A):
   
    def __init__(self, x: float, y: float) -> None:
      super().__init__(x)
      self.yy = y

    def __str__(self) -> str:
       return f"B: {self.xx + self.yy}"
    
b=B(10,20)
print(b)

B: 30


In [ ]:
class A:
   def __init__(self, x: float) -> None:
     self.xx = x

class B(A):
   
   def __init__(self, x: float, y: float) -> None:
      super().__init__(x)
      self.yy = y

   def __str__(self) -> str:
       return f"B: {self.xx + self.yy}"
    

In [67]:
import numpy as np

def neg(A: np.ndarray) -> np.ndarray:
    A[A < 0] = 0
    return -1 * A

#Example
A = np.array([
    [ 1, -2,  3],
    [-4,  5, -6],
    [ 7,  8,  0],
])

print(neg(A))


[[-1  0 -3]
 [ 0 -5  0]
 [-7 -8  0]]


In [ ]:
# Question 1:
def my_update(D1,D2):
    for k in D2:
        if k in D1:
            D1[k],D2[k]=D2[k],D1[k]
        else:
            D1[k]=D2[k]

'''
D1={1:10,2:20}
D2={1:100,3:30}
my_update(D1,D2)
print(D1=={1: 100, 2: 20, 3: 30},D2=={1: 10, 3: 30})

D1={1:10,2:20}
D2={3:30,4:40}
my_update(D1,D2)
print(D1=={1: 10, 2: 20, 3: 30,4:40},D2=={3:30,4:40})

D1={1:10,2:20}
D2={1:100,2:200}
my_update(D1,D2)
print(D1=={1:100,2:200},D2=={1:10,2:20})

D1={1:10,2:20}
D2={}
my_update(D1,D2)
print(D1=={1:10,2:20},D2=={})

D1={}
D2={1:10,2:20}
my_update(D1,D2)
print(D1=={1:10,2:20},D2=={1:10,2:20})
'''


# Question 2:
def printgen(G):
    GL=list(G)
    for e in GL:
        print(e)
    for e in GL:
        print(e)

'''
X=(i for i in range(4))
printgen(X)

L=[[1,2],[3,4],[5,6]]
Y=(e for e in L)
printgen(Y)

printgen(e for e in [])

printgen(v for v in range(10) if v%2==0)
'''

# Question 3:

def merge(L1, L2):
    
    RES = []
    i = 0
    j = 0
    
    while i<len(L1) and j<len(L2):
        if L1[i] <= L2[j]:
            RES.append(L1[i])
            i += 1
        else:
            RES.append(L2[j])
            j += 1

    if i<len(L1):
        RES += L1[i:]
    else:
        RES += L2[j:]

    return RES
    

'''

print(merge([1,3,5], [0,2,4,6,8,10]))
print(merge([], []))
print(merge([1,3,5], []))
print(merge([], [1,3,6]))
print(merge([100], list(range(1,99,3))))
print(merge([1,3,5], [100,300,500]))
print(merge([1],[100]))

'''

# Question 4:
class B(A):
    def __init__(self,x,y):
        super().__init__(x)
        self.yy=y
    def __str__(self):
        return 'B: '+str(self.xx+self.yy)
'''
b=B(10,20)
print(b) 

b=B(0,0)
print(b) 

b=B(100,200)
print(b) 

'''

# Question 5:
import numpy as np

def neg(A):
    A[A < 0] = 0
    return -1*A

"""
#test 0
A = np.array([[1,-2,3],
              [-4,5,-6],
              [7,8,0]])
print(neg(A))

#test 1
A = np.array([[-5,-6,7,-1],
              [8,9,-10,0],
              [11,12,13,3]])
print(neg(A))

#test 2
A = np.array([[-2,-4],
              [8,10],
              [14,-16]])
print(neg(A))

#test 3
A = np.array([[1, -3, 0]])
print(neg(A))
"""
